export const courseList = [
  {
    key: 1,
    img: '/src/assets/next+react.png',
    name: 'Next.js & React - The Complete Guide (incl. Two Paths!)',
    desc: 'Learn NextJS from the ground up and build production-ready, fullstack ReactJS apps with the NextJS framework!',
    author: 'Maximilian Schwarzmüller',
    rating: 4.8,
    price: 14.99,
  },
  {
    key: 2,
    img: '/src/assets/Learn-Reactjs.png',
    name: 'React - The Complete Guide',
    desc: 'Dive in and learn React.js from scratch! Learn Reactjs, Hooks, Redux, React Routing, Animations, Next.js and way more!',
    author: 'Academind by Maximilian Schwarzmüller',
    rating: 4.6,
    price: 19.99,
  },
  {
    key: 3,
    img: '/src/assets/react_js.png',
    name: 'Complete React Developer in 2023 (w/ Redux, Hooks, GraphQL)',
    desc: 'Updated! Become a Senior React Developer. Build a massive E-commerce app with Redux, Hooks, GraphQL, Stripe, Firebase',
    author: 'Andrei Neagoie, Yihua Zhang, Zero to Mastery',
    rating: 4.6,
    price: 14.99,
  },
  {
    key: 4,
    img: '/src/assets/Pros and Cons of React JS and React Native.png',
    name: 'React Tutorial and Projects Course (2022)',
    desc: 'Learn React by Building 25+ Interesting Projects',
    author: 'John Smilga',
    rating: 4.7,
    price: 13.99,
  },
  {
    key: 5,
    img: '/src/assets/javascript.png',
    name: 'JavaScript: Understanding the Weird Parts',
    desc: `An advanced JavaScript course for everyone! Scope, closures, prototypes, 'this', build your own framework, and more.`,
    author: 'Anthony Alicea',
    rating: 4.8,
    price: 16.99,
  },
  {
    key: 6,
    img: '/src/assets/React-js-projects-for-beginners-with-source-code.png',
    name: 'Modern React with Redux [2023 Update]',
    desc: 'Master React and Redux Toolkit. Includes RTK Query, tons of custom hooks, and more! Course 100% Updated November 2022',
    author: 'Stephen Grider',
    rating: 4.7,
    price: 16.99,
  },
];
